
moto_360:
  title: Moto 360 Design Face-Off
  last_modified: 2016-10-15
  cta: Watch This
  description: An entry to the Moto 360 Design Face-Off, it was selected as one of the top 10 out of 1300 entries by a panel of judges, and then placed second through popular-choice voting. The design was featured on <a href='http://www.theverge.com/2014/6/19/5823664/moto-360-watch-face-designs-photo-essay' title="The Verge - 'It fits the watch perfectly.'" target="_blank">The Verge</a>, <a href="http://www.huffingtonpost.co.uk/2014/06/19/moto360-concept-designs_n_5511549.html" title="Huffington Post" target="_blank">Huffington Post</a>, and <a href="http://www.digitaltrends.com/mobile/best-moto-360-watch-face-designs/" title="Digital Trends - '...traditional and minimalistic.'" target="_blank">Digital Trends</a> among many others.
  url: https://d2vez5w0ugqe83.cloudfront.net/graphic_design/watch.gif
  tags:
    - Wearables
    - Watch

rescue_tech:
  title: Rescue Tech
  last_modified: 2016-10-15
  description: A logo created for the health and safety training company, Rescue Tech. I created it in conjunction with the design and development of their website, <a href="http://rescuetech.training/" title="Rescue Tech Health and Safety Services" target="_blank">rescuetech.training</a>.
  transparent: true
  url: https://d2vez5w0ugqe83.cloudfront.net/graphic_design/rescue-tech.svg
  tags:
    - Branding
    - Logo

skrillex:
  title: Skrillex
  last_modified: 2016-10-15
  description: A study in applying a brand's (or in this case, artist's) visual style to a new piece. I enjoy the energy of Skrillex's album covers, and decided to take a stab at it myself.
  url: https://d2vez5w0ugqe83.cloudfront.net/graphic_design/skrillex.jpg
  tags:
    - Practice
    - Album Cover

teichert:
  title: Teichert ERT
  last_modified: 2016-10-15
  description: I was commissioned to create a logo for the construction company Teichert's new Emergency Response team. The logo was designed to work within their existing brand aesthetic.
  transparent: true
  url: https://d2vez5w0ugqe83.cloudfront.net/graphic_design/teichert-ert.svg
  tags:
    - Branding
    - Logo
