
steve_jobs:
  title: Steve Jobs Portrait
  last_modified: 2016-10-15
  description: Based on the book cover of the 2011 biography written by Walter Isaacson, this charcoal portrait was illustrated in 2012 on 24x36 charcoal paper in honor of the late Steve Jobs. Completed over the course of 40 hours, it was a new experience for me working on this level of detail, and also one of my first ventures into portraiture.
  url: https://d2vez5w0ugqe83.cloudfront.net/illustration/jobs.jpg
  tags:
    - Charcoal
    - Portrait
    - Black & White

faraway:
  title: Far Away
  last_modified: 2016-10-15
  description: Created in 2011 prior to attending illustration school, Far Away is one of the first digital illustrations I ever made. The landscape is lightly based on Yavin IV from Star Wars, orbiting the gas giant planet of Yavin.
  url: https://d2vez5w0ugqe83.cloudfront.net/illustration/faraway.jpg
  tags:
    - Digital
    - Landscape
    - Science Fiction

yoda:
  title: Yoda
  last_modified: 2016-10-15
  description: A familiar face, I created this digital portrait of Jedi Master Yoda in 2012 while in school. This illustration is based on the statue that tops the fountain at the Lucasfilm headquarters in the Presidio in San Francisco. I frequented the campus to relax and sketch in between my school work. 
  url: https://d2vez5w0ugqe83.cloudfront.net/illustration/yoda.jpg
  tags:
    - Digital
    - Protrait
    - Science Fiction
    - Black & White

war:
  title: War Torn
  last_modified: 2016-10-15
  description: A nameless, war torn city street. This illustration drawn in 2012 using ink, markers, and Adobe Photoshop was a practice in single-point perspective, and lighting. Not based on anything specific, it was great practice in using reference photos to create scenes straight from the imagination.
  url: https://d2vez5w0ugqe83.cloudfront.net/illustration/war.png
  tags:
    - Digital
    - Ink
    - Mixed Media
    - Cityscape

missile:
  title: Missile
  last_modified: 2016-10-15
  description: Another war scene, this piece was a practice in two-point perspective, and was primarily painted in Photoshop with the groundwork done with ink.
  url: https://d2vez5w0ugqe83.cloudfront.net/illustration/missile.png
  tags:
    - Digital
    - Ink
    - Mixed Media
    - Cityscape
