
homepage:
  title: Homepage Redesign
  last_modified: 2016-10-15
  cta: New Homepage
  description: As we were participating in <a href="http://gsvlabs.com/pioneer-accelerator/" title="Global Silicon Valley Labs Pioneer Accelerator" target="_blank">GSV Labs Pioneer Accelerator</a>, we took some time to focus on what the core of the product should be, and the centerpiece of that was the homepage. Originally, we had a static landing page that explained the product, but the team and I had a better idea. We decided to let people browse the product without signing up, so we could keep marketing copy light, and let the product explain itself.
  url: https://d2vez5w0ugqe83.cloudfront.net/table/homepage.png
  tags:
    - Interface Design
    - User Experience Design

table_layout:
  title: Improving Interface Clarity
  last_modified: 2016-10-15
  cta: Interface Clarity
  description: One element to Table is its' communication platform. What I had found when I joined the team was that the interface was difficult to navigate, and used space in an inefficient manner. I designed a layout utilizing a sidebar that would not only use space in a more efficient way, but also expose critical functions within the chat, display the description for the Table, and make it easier to find files and media that was sent within the platform.
  url: https://d2vez5w0ugqe83.cloudfront.net/table/table-layout.png
  before: https://d2vez5w0ugqe83.cloudfront.net/table/table-layout--before.png
  tags:
    - Interface Design
    - User Experience Design

iconography:
  title: Iconographic Unity
  last_modified: 2016-10-15
  cta: Table Iconography
  description: One of the goals I set while working at Table was to make the product, and its functionality clear. I saw that one way we could build towards this goal was to create a unified language of symbols that were understandable and representative of the brand, as the current icons used were often vague and lacked consistency. My team and I developed a system for creating a brand-unique set of icons that could be used across our apps, and website.
  url: https://d2vez5w0ugqe83.cloudfront.net/table/icons.svg
  tags:
    - Graphic Design
    - Iconography

media_viewer:
  title: Adding Functionality
  last_modified: 2016-10-15
  cta: Adding Functionality
  description: When I began working at Table, a large focus of the company was on its communication platform. When we decided that it was time to revamp the media-viewer with comments, social sharing, and likes, I worked on a way to do all of this in a clear, and usable way.
  url: https://d2vez5w0ugqe83.cloudfront.net/table/media-viewer.png
  before: https://d2vez5w0ugqe83.cloudfront.net/table/media-viewer--before.png
  tags:
    - Interface Design
    - User Experience Design
